name: 'Build FFmpeg'
description: 'Build FFmpeg from source with required libraries'
inputs:
  version:
    description: 'FFmpeg version tag to build'
    required: false
    default: 'n8.0.1'
runs:
  using: 'composite'
  steps:
    - name: Cache FFmpeg
      id: cache-ffmpeg
      uses: actions/cache@v4
      with:
        path: ~/ffmpeg-install
        key: ffmpeg-${{ inputs.version }}-${{ runner.os }}
    - name: Install build dependencies
      if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sudo add-apt-repository universe -y
        sudo add-apt-repository multiverse -y
        sudo add-apt-repository restricted -y
        sudo sed -i 's/Types: deb$/Types: deb deb-src/g' /etc/apt/sources.list.d/*.sources || true
        sudo apt-get update
        sudo apt-get build-dep ffmpeg -y
    - name: Build FFmpeg
      if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
      shell: bash
      run: |
        git clone --depth 1 --branch ${{ inputs.version }} --single-branch https://git.ffmpeg.org/ffmpeg.git ffmpeg
        cd ffmpeg
        ./configure --prefix=$HOME/ffmpeg-install --disable-x86asm --enable-gpl \
                    --enable-nonfree --disable-programs --disable-doc \
                    --enable-shared --enable-libtheora --enable-libvpx \
                    --enable-libmp3lame --enable-libvorbis --enable-libsoxr
        make -j4
        make install
    - name: Install FFmpeg
      shell: bash
      run: |
        sudo cp -r ~/ffmpeg-install/* /usr/
        sudo ldconfig
